// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrBY8ep2TieRT6aTdFFKWyTEoAVzveqk',
    appId: '1:117974400863:web:1b68306f3953b53591c0ea',
    messagingSenderId: '117974400863',
    projectId: 'baby-names-app-db-771c1',
    authDomain: 'baby-names-app-db-771c1.firebaseapp.com',
    databaseURL: 'https://baby-names-app-db-771c1.firebaseio.com',
    storageBucket: 'baby-names-app-db-771c1.appspot.com',
    measurementId: 'G-JY42YTFSZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABND5FLziQYQ6WqBkY3tfCIl9dNkGY3w4',
    appId: '1:117974400863:android:2b6415d496c68df691c0ea',
    messagingSenderId: '117974400863',
    projectId: 'baby-names-app-db-771c1',
    databaseURL: 'https://baby-names-app-db-771c1.firebaseio.com',
    storageBucket: 'baby-names-app-db-771c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZFQbG1abOHtZUEbNnRuVBMrVNfIlKe0',
    appId: '1:117974400863:ios:6261a0726770ab8991c0ea',
    messagingSenderId: '117974400863',
    projectId: 'baby-names-app-db-771c1',
    databaseURL: 'https://baby-names-app-db-771c1.firebaseio.com',
    storageBucket: 'baby-names-app-db-771c1.appspot.com',
    iosClientId: '117974400863-a1oimm1uo46sap0vv7tga4fjraaie90v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZFQbG1abOHtZUEbNnRuVBMrVNfIlKe0',
    appId: '1:117974400863:ios:6261a0726770ab8991c0ea',
    messagingSenderId: '117974400863',
    projectId: 'baby-names-app-db-771c1',
    databaseURL: 'https://baby-names-app-db-771c1.firebaseio.com',
    storageBucket: 'baby-names-app-db-771c1.appspot.com',
    iosClientId: '117974400863-a1oimm1uo46sap0vv7tga4fjraaie90v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExamples',
  );
}
